### ISSUE TITLE
Code screenshot not work in 2016.3 version

### ISSUE THREAD

**Issue by muhghazaliakbar** [amaembo/screenshoter#1]
i tried to screenshot the code and paste into microsoft word document. but not work.

**Comment by muhghazaliakbar** [comment]
Sorry, i don't know need to block the code which want to take screenshot :)

**Comment by amaembo** [comment]
Thank you for the interest to my plugin. I added a hint to readme.md to make this clear.

**Comment by muhghazaliakbar** [comment]
also add MacOs command to your readme :)

**Comment by amaembo** [comment]
And which key combination is used in MacOS? Sorry, I don't have a Mac to test this.

**Comment by muhghazaliakbar** [comment]
option+command+shift+A
<img width="314" alt="screenshot 2017-03-06 23 11 19" src="https://cloud.githubusercontent.com/assets/8321936/23615853/bfd27446-02c2-11e7-85fe-20d258f543e4.png">

**Comment by amaembo** [comment]
Thanks, added.

**Comment by muhghazaliakbar** [comment]
cool ^^
