### ISSUE TITLE
Plugin doesn't work with pyCharm 2019.1

### ISSUE THREAD

**Issue by Drey** [amaembo/screenshoter#15]
It seems like this pretty useful plugin doesn't work with pyCharm 2019.1.

When I try to copy my code as an image nothing happens.

**Comment by amaembo** [comment]
You should select some text in the editor, then place a hotkey. The image will be placed in the clipboard. Does it work for you? Are you trying plugin for the first time or it worked for you before and stopped working in PyCharm 2019.1?

**Comment by Drey** [comment]
The plugin stopped working in PyCharm 2019.1. It perfectly works with the previous PyCharm version.

**Comment by amaembo** [comment]
I tried the latest plugin version with PyCharm 2019.1.3 (Professional Edition) Build #PY-191.7479.30, built on May 29, 2019, JRE: 11.0.2+9-b159.60 amd64, Windows 10 10.0. It works perfectly for me. Is the problem still actual for you? Could you please share exact version of your PyCharm installation (including JRE) as well as your OS version? Thanks.

**Comment by amaembo** [comment]
Looks obsolete
