### ISSUE TITLE
Plugin or plugin hotkey not work in rider.

### ISSUE THREAD

**Issue by MairwunNx** [amaembo/screenshoter#16]
When i click `ctrl + shift + alt + a` i can't get screenshot of selected code. But it normal work in Idea.

---

**Plugin version**: `Latest Version`
**JetBrains Rider**: `2019.1.1`
**Build**: `#RD-191.6733.985, built on May 1, 2019`
**Windows**: `10, 1809`

---

Also, the exception is not thrown, perhaps this is because some hotkeys call another menu.
![image](https://user-images.githubusercontent.com/39625750/58026661-a1302380-7b1f-11e9-97d5-e78b5a907f23.png)

**Comment by amaembo** [comment]
I think it's possible to reassign the hotkey used in plugin by default via Keymap settings? It's hard to find a hotkey which doesn't clash with anything in every possible IDEA-based product, especially taking into account that other plugins may want to register more hotkeys as well.
