### ISSUE TITLE
I can't use it normally in ubuntu

### ISSUE THREAD

**Issue by huangsiyuan924** [amaembo/screenshoter#18]
I tried to use it normally in Windows, but not in Ubuntu.
It show “Image was copied to the clipboard”， but nothing happens when pasting

**Comment by amaembo** [comment]
Hello! Sorry I'm not using Ubuntu. You are welcome to submit a pull request.

**Comment by Miha-x64** [comment]
Works for me on Ubuntu.
@huangsiyuan924, where you've tried to paste it?

**Comment by amaembo** [comment]
Please comment if the problem is still actual
