### ISSUE TITLE
Alert the user if they have selected too much code

### ISSUE THREAD

**Issue by MartiUK** [amaembo/screenshoter#29]
After trying to screenshot an entire 80 line file, I got the "Image was copied to the clipboard" but nothing was actually copied to the clipboard. Screenshotting a smaller amount of lines worked as expected.

**Comment by amaembo** [comment]
A warning will be issued when attempting to copy or save a too big image:

![image](https://user-images.githubusercontent.com/5114450/114298166-3f944c00-9adf-11eb-9950-73a1fff3ad21.png)
