### ISSUE TITLE
Expand the scope of screenshots

### ISSUE THREAD

**Issue by way1212** [amaembo/screenshoter#35]
[http://m.qpic.cn/psc?/V50t9myH1Y2xpo3qGYlD0X7TJk006X0V/bqQfVz5yrrGYSXMvKr.cqXwm5NRCQuIvp6DjK1.vi.Qdhl2OAU6p7Ck1n05OK7Mze3Jes66MLKlHgbs5o1.cfli4WEkZrwKKSLm7ScWGrgs!/mnull&bo=AwbdAgMG3QIDByI!&rf=photolist&t=5](url)

I hope you can add the number of lines beside the code to the screenshot and expand the screenshot area to make the screenshot more beautiful.

**Comment by amaembo** [comment]
You can set the Padding in the settings to expand the screenshot area.
