### ISSUE TITLE
IDEA 2023.1 compatibility

### ISSUE THREAD

**Issue by TheMrMilchmann** [amaembo/screenshoter#36]
Version 1.8 of the plugin declares the compatibility range `213—223.*` which excludes IDEA 2023.1 (231.*). Thus, when updating IDEA, the plugin is automatically "updated" to 1.7.1 despite this version being older. However, from what I can tell, 1.7.1 is working fine for now.

**Comment by amaembo** [comment]
Sorry for the inconvenience. I've removed until-version
https://plugins.jetbrains.com/plugin/9406-code-screenshots/versions/stable/328590
Please check.

**Comment by TheMrMilchmann** [comment]
I can confirm that `1.8.1` works fine for me and is detected correctly by recent IDEA versions now. Thanks!
